export const elements = {
  theModal: document.querySelector(".houseModal"),
  modalButton: document.querySelector(".button"),
  modalQuestion1: document.querySelector(".houseModal__body__question--1"),
  modalHousePrice: document.querySelector(".housePrice"),
  modalHousePriceBtn: document.querySelector("#aq2"),
  modalDeposit: document.querySelector(".deposit"),
  modalRate: document.querySelector(".rate"),
  modalTermTime: document.querySelector(".termTime"),
  modalq1Btn: document.querySelector("#q1Btn"),
  modalq2Btn: document.querySelector("#q2Btn"),
  modalq3Btn: document.querySelector("#q3Btn"),
  modalq4Btn: document.querySelector("#q4Btn"),
  modalSubmit: document.querySelector(".submit"),
  firstFrom: document.querySelector(".firstTimeBuyer"),
  formHousePrice: document.querySelector(".formPrice"),
  formDeposit: document.querySelector(".formDeposit"),
  formRate: document.querySelector(".formRate"),
  formTermTime: document.querySelector(".formTerm"),
  formStampDuty: document.querySelector(".formStampDuty"),
  formTotalCash: document.querySelector(".formTotalCash"),
  formMonthlyMortgage: document.querySelector(".formMonthlyMortgage"),
};
